### PR TITLE
Add loongarch support and LSX SIMD optimizations

### PR DESCRIPTION
**Pull request by XiWeiGu**
Enable LSX by default: ./autogen.sh --maintainer && ./configure && make
Disable LSX: ./autogen.sh --maintainer && ./configure --enable-loongarch-lsx=no && make

### CODE REVIEW

**Comment by XiWeiGu** [comment]
@ctruta , Could you please take some time to review the code?

**Review by ctruta — APPROVED** [review]
Looks good to me.

**Comment by ctruta** [comment]
Oops I almost missed one thing: that the libpng developers (not the users) are the ones who run
`./autogen.sh --maintainer`
I'll do this for you.

**Comment by ctruta** [comment]
Done. See a7fe3414e5271b51a8103be47a582ca8e276f84b.

... but now, after landing the last three commits, `./configure --enable-hardware-optimizations` is broken, and we must have it fixed before we ship the next release. Could you please take a look?

While at it, could you also verify if I updated the AUTHORS file correctly?

**Comment by XiWeiGu** [comment]
I will address it promptly.

**Comment by ctruta** [comment]
Thank you. Could you please also have a look at compilation with
gcc -Wundef
because that one is complaining as well.

**Comment by XiWeiGu** [comment]
> Done. See [a7fe341](https://github.com/glennrp/libpng/commit/a7fe3414e5271b51a8103be47a582ca8e276f84b).
> 
> ... but now, after landing the last three commits, `./configure --enable-hardware-optimizations` is broken, and we must have it fixed before we ship the next release. Could you please take a look?


I apologize for the oversight and appreciate your reminder. The issue has been addressed in the PR #526

**Comment by XiWeiGu** [comment]
> While at it, could you also verify if I updated the AUTHORS file correctly?

"ZhangLixia" has resigned and is no longer maintaining the Loongson ecosystem. I suggest replacing her with "JinBo," who is the primary contributor to LoongArch LSX optimizations.

**Comment by XiWeiGu** [comment]
> Thank you. Could you please also have a look at compilation with gcc -Wundef because that one is complaining as well.

Reiterating my gratitude. PR #527 has already fixed this issue.

**Comment by ctruta** [comment]
> > While at it, could you also verify if I updated the AUTHORS file correctly?
> 
> "ZhangLixia" has resigned and is no longer maintaining the Loongson ecosystem. I suggest replacing her with "JinBo," who is the primary contributor to LoongArch LSX optimizations.

This is very good to know, thanks. I added JinBo to the list of authors.

About ZhangLixia, I'm still keeping her name in there, because she co-authored source code such as `mips/filter_mmi_inline_assembly.c`, in official Loongson capacity, and that merit is not going to "expire" 🙂

And, if I may please ask for yet one more favour. The Authors file is in ASCII right now, but I want to convert it to UTF-8 eventually. Could you please send me the correct Chinese spellings for all Loongson contributors?

**Comment by jinboson** [comment]
> Could you please send me the correct Chinese spellings for all Loongson contributors?

GuXiWei    -->   顾希伟
JinBo         -->   金波
ZhangLixia -->   张利霞

Hope this may help. Thx!

**Pull request merged**
