### PR TITLE
Clean up riffled palette in more places, fix tests

### LINKED ISSUE #266: libpng 1.6.36 build failure on linux arm64 (Debian and Ubuntu)
See e.g. https://buildd.debian.org/status/fetch.php?pkg=libpng1.6&arch=arm64&ver=1.6.36-1&stamp=1545917181&raw=0
```
make  check-TESTS
make[3]: Entering directory '/<<PKGBUILDDIR>>'
make[4]: Entering directory '/<<PKGBUILDDIR>>'
PASS: tests/pngtest
PASS: tests/pngtest-badpngs
PASS: tests/pngvalid-gamma-16-to-8
PASS: tests/pngvalid-gamma-threshold
FAIL: tests/pngvalid-gamma-expand16-transform
PASS: tests/pngvalid-progressive-interlace-standard
PASS: tests/pngvalid-gamma-expand16-background
PASS: tests/pngvalid-gamma-background
PASS: tests/pngvalid-gamma-transform
PASS: tests/pngvalid-progressive-standard
PASS: tests/pngvalid-standard
PASS: tests/pngvalid-progressive-size
PASS: tests/pngvalid-gamma-sbit
FAIL: tests/pngvalid-transform
PASS: tests/pngvalid-gamma-alpha-mode
PASS: tests/pngvalid-gamma-expand16-alpha-mode
PASS: tests/pngstest-linear-alpha
PASS: tests/pngunknown-IDAT
PASS: tests/pngunknown-discard
PASS: tests/pngunknown-if-safe
PASS: tests/pngunknown-sAPI
PASS: tests/pngunknown-sTER
PASS: tests/pngunknown-save
PASS: tests/pngunknown-vpAg
PASS: tests/pngstest-1.8-alpha
PASS: tests/pngimage-quick
PASS: tests/pngstest-linear
PASS: tests/pngstest-1.8
PASS: tests/pngstest-none-alpha
PASS: tests/pngstest-sRGB-alpha
PASS: tests/pngstest-none
PASS: tests/pngstest-sRGB
PASS: tests/pngimage-full
=====================================
   libpng 1.6.36: ./test-suite.log
=====================================

# TOTAL: 33
# PASS:  31
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/pngvalid-gamma-expand16-transform
=============================================

Gamma correction error summary

The printed value is the maximum error in the pixel values
calculated by the libpng gamma correction code.  The error
is calculated as the difference between the output pixel
value (always an integer) and the ideal value from the
libpng specification (typically not an integer).

Expect this value to be less than .5 for 8 bit formats,
less than 1 for formats with fewer than 8 bits and a small
number (typically less than 5) for the 16 bit formats.
For performance reasons the value for 16 bit formats
increases when the image file includes an sBIT chunk.
gamma 0.455->1.000: read indexed-colour[0] 8 bit: memory lost (list follows):
	1024 bytes @ 0xaaaac9b84440

Basic gamma correction:
  2 bit gray:  127.07023
  4 bit gray:  127.07023
  8 bit gray:  128.32752
  8 bit color: 128.32752
  indexed:     128.32752
 16 bit gray:  0.74080
 16 bit color: 0.74080
pngvalid: 
pngvalid: 1 errors, 0 warnings
FAIL: pngvalid --strict --gamma-transform --expand16 (floating point arithmetic)
FAIL tests/pngvalid-gamma-expand16-transform (exit status: 1)

FAIL: tests/pngvalid-transform
==============================

transform: +rgb_to_gray: read indexed-colour[0] 8 bit: memory lost (list follows):
	1024 bytes @ 0xaaaad27974c0
pngvalid: 
pngvalid: 1 errors, 0 warnings
FAIL: pngvalid --strict --transform (floating point arithmetic)
FAIL tests/pngvalid-transform (exit status: 1)

============================================================================
Testsuite summary for libpng 1.6.36
============================================================================
# TOTAL: 33
# PASS:  31
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to png-mng-implement@lists.sourceforge.net
```

### PR DESCRIPTION
**Pull request by richard-townsend-arm**
This PR adds additional cleanup logic in `png_read_destroy` to deallocate the palette if necessary and also fixes the `pngvalid.c` regression tests to call this method. This should fix #266.

### CODE REVIEW

**Comment by richard-townsend-arm** [comment]
Supersedes #271 with a corrected issue number.

**Comment by LocutusOfBorg** [comment]
ok this fixes my issue thanks

**Comment by tangyaofang** [comment]
I see it in version 1.6.37, the latest code is:
#if defined(PNG_READ_EXPAND_SUPPORTED) && \
     Defined(PNG_ARM_NEON_IMPLEMENTATION)
    Png_free(png_ptr, png_ptr->riffled_palette);
    Png_ptr->riffled_palette = NULL;
#endif

Your problem should be solved in version 1.6.37.

**Comment by ctruta** [comment]
This was indeed fixed in 1.6.37. (I had forgotten to close this issue at that time.)

**Pull request closed without merging**
