### PR TITLE
FIX: decode fail on image with invalid eXIf chunk

### PR DESCRIPTION
**Pull request by nju04zq**
libpng failed to decode this image, http://p3-tt.byteimg.com/pgc-image/Rksod8L9ccqahW~tplv-obj.image.
Change-Id: Ibe5cbff3411126696279ca1d81627d4f9325cfed

### CODE REVIEW

**Comment by wader** [comment]
Hello, i've run into images with this issue and this fix seems to fix them. Is this fix planned for next stable release?

Any ideas what programs that write these kind of exif chunks?

**Comment by LocutusOfBorg** [comment]
@ctruta can you please have a look here?

**Comment by ctruta** [comment]
Hi! I applied this fix, with many thanks and apologies for the very large delay.

**Comment by LocutusOfBorg** [comment]
yay thanks!

**Pull request merged**
