### PR TITLE
Fix for #424

### PR DESCRIPTION
**Pull request by thealberto**
Hi @ctruta ,
as promised I have worked a little bit on #424 and managed to reproduce it using `oss-fuzz`. The issue is due to the fact that `png_malloc_base` does not return an initialized chunk of memory so it might happen that in some part of the code that memory chunk is just read.

I think this patch should ensure that similar bugs, hopefully, won't be present anymore :)

I have tested the patch with the same 2 reproducers and `oss-fuzz` seems fine with it. Unfortunately I couldn't reproduce the bug with the original reproducers provided in the issue.

Finally, I have also update the `AUTHORS` file. Considering that every name was in alphabetical order I had to put mine on the top unfortunately. Feel free to move it of course.

# Before the patch

```
➜  oss-fuzz git:(master) ✗ sudo python3 infra/helper.py reproduce libpng libpng_read_fuzzer ../oss/issue424/reproducer 
INFO:root:Running: docker run --rm --privileged --platform linux/amd64 -i -v /home/alberto/progetti/oss-fuzz/build/out/libpng:/out -v /home/alberto/progetti/oss/issue424/reproducer:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce libpng_read_fuzzer -runs=100.
+ FUZZER=libpng_read_fuzzer
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer libpng_read_fuzzer -runs=100 /testcase
/out/libpng_read_fuzzer -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase -dict=png.dict < /dev/null
Dictionary: 28 entries
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 840971625
INFO: Loaded 1 modules   (5499 inline 8-bit counters): 5499 [0x6f7db0, 0x6f932b), 
INFO: Loaded 1 PC tables (5499 PCs): 5499 [0x691310,0x6a6ac0), 
/out/libpng_read_fuzzer: Running 1 inputs 100 time(s) each.
Running: /testcase
==17==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5d009f in png_read_filter_row_paeth_multibyte_pixel /src/libpng/pngrutil.c:4079:11
    #1 0x5ca17d in OSS_FUZZ_png_read_filter_row /src/libpng/pngrutil.c:4140:7
    #2 0x568b11 in OSS_FUZZ_png_read_row /src/libpng/pngread.c:548:10
    #3 0x4a7d50 in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:200:7
    #4 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #5 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #6 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #7 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7f8a98988082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #9 0x41f62d in _start (/out/libpng_read_fuzzer+0x41f62d)

DEDUP_TOKEN: png_read_filter_row_paeth_multibyte_pixel--OSS_FUZZ_png_read_filter_row--OSS_FUZZ_png_read_row
  Uninitialized value was stored to memory at
    #0 0x5cfb07 in png_read_filter_row_paeth_multibyte_pixel /src/libpng/pngrutil.c:4052:14
    #1 0x5ca17d in OSS_FUZZ_png_read_filter_row /src/libpng/pngrutil.c:4140:7
    #2 0x568b11 in OSS_FUZZ_png_read_row /src/libpng/pngread.c:548:10
    #3 0x4a7d50 in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:200:7
    #4 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #5 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #6 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #7 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7f8a98988082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: png_read_filter_row_paeth_multibyte_pixel--OSS_FUZZ_png_read_filter_row--OSS_FUZZ_png_read_row
  Uninitialized value was stored to memory at
    #0 0x5cfb07 in png_read_filter_row_paeth_multibyte_pixel /src/libpng/pngrutil.c:4052:14
    #1 0x5ca17d in OSS_FUZZ_png_read_filter_row /src/libpng/pngrutil.c:4140:7
    #2 0x568b11 in OSS_FUZZ_png_read_row /src/libpng/pngread.c:548:10
    #3 0x4a7d50 in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:200:7
    #4 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #5 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #6 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #7 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7f8a98988082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: png_read_filter_row_paeth_multibyte_pixel--OSS_FUZZ_png_read_filter_row--OSS_FUZZ_png_read_row
  Uninitialized value was created by a heap allocation
    #0 0x453ef0 in __interceptor_malloc /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:895:3
    #1 0x4a6401 in limited_malloc(png_struct_def*, unsigned long) /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:90:10
    #2 0x56530f in OSS_FUZZ_png_malloc_base /src/libpng/pngmem.c:91:17
    #3 0x56530f in OSS_FUZZ_png_malloc /src/libpng/pngmem.c:179:10
    #4 0x5cd6e8 in OSS_FUZZ_png_read_start_row /src/libpng/pngrutil.c:4607:44
    #5 0x5681e2 in OSS_FUZZ_png_read_update_info /src/libpng/pngread.c:275:10
    #6 0x4a7b4d in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:192:3
    #7 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #8 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #9 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #10 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #11 0x7f8a98988082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: __interceptor_malloc--limited_malloc(png_struct_def*, unsigned long)--OSS_FUZZ_png_malloc_base
SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/libpng/pngrutil.c:4079:11 in png_read_filter_row_paeth_multibyte_pixel
Unique heap origins: 58
Stack depot allocated bytes: 9764880
Unique origin histories: 29
History depot allocated bytes: 196608
Exiting
➜  oss-fuzz git:(master) ✗ 
```

```
➜  oss-fuzz git:(master) ✗ sudo python3 infra/helper.py reproduce libpng libpng_read_fuzzer ../oss/issue424/reproducer2 
INFO:root:Running: docker run --rm --privileged --platform linux/amd64 -i -v /home/alberto/progetti/oss-fuzz/build/out/libpng:/out -v /home/alberto/progetti/oss/issue424/reproducer2:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce libpng_read_fuzzer -runs=100.
+ FUZZER=libpng_read_fuzzer
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer libpng_read_fuzzer -runs=100 /testcase
/out/libpng_read_fuzzer -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase -dict=png.dict < /dev/null
Dictionary: 28 entries
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1108405722
INFO: Loaded 1 modules   (5499 inline 8-bit counters): 5499 [0x6f7db0, 0x6f932b), 
INFO: Loaded 1 PC tables (5499 PCs): 5499 [0x691310,0x6a6ac0), 
/out/libpng_read_fuzzer: Running 1 inputs 100 time(s) each.
Running: /testcase
==17==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5d009f in png_read_filter_row_paeth_multibyte_pixel /src/libpng/pngrutil.c:4079:11
    #1 0x5ca17d in OSS_FUZZ_png_read_filter_row /src/libpng/pngrutil.c:4140:7
    #2 0x568b11 in OSS_FUZZ_png_read_row /src/libpng/pngread.c:548:10
    #3 0x4a7d50 in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:200:7
    #4 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #5 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #6 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #7 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7f99aad07082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #9 0x41f62d in _start (/out/libpng_read_fuzzer+0x41f62d)

DEDUP_TOKEN: png_read_filter_row_paeth_multibyte_pixel--OSS_FUZZ_png_read_filter_row--OSS_FUZZ_png_read_row
  Uninitialized value was stored to memory at
    #0 0x5cfb07 in png_read_filter_row_paeth_multibyte_pixel /src/libpng/pngrutil.c:4052:14
    #1 0x5ca17d in OSS_FUZZ_png_read_filter_row /src/libpng/pngrutil.c:4140:7
    #2 0x568b11 in OSS_FUZZ_png_read_row /src/libpng/pngread.c:548:10
    #3 0x4a7d50 in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:200:7
    #4 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #5 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #6 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #7 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7f99aad07082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: png_read_filter_row_paeth_multibyte_pixel--OSS_FUZZ_png_read_filter_row--OSS_FUZZ_png_read_row
  Uninitialized value was stored to memory at
    #0 0x5cfb07 in png_read_filter_row_paeth_multibyte_pixel /src/libpng/pngrutil.c:4052:14
    #1 0x5ca17d in OSS_FUZZ_png_read_filter_row /src/libpng/pngrutil.c:4140:7
    #2 0x568b11 in OSS_FUZZ_png_read_row /src/libpng/pngread.c:548:10
    #3 0x4a7d50 in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:200:7
    #4 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #5 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #6 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #7 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7f99aad07082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: png_read_filter_row_paeth_multibyte_pixel--OSS_FUZZ_png_read_filter_row--OSS_FUZZ_png_read_row
  Uninitialized value was created by a heap allocation
    #0 0x453ef0 in __interceptor_malloc /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:895:3
    #1 0x4a6401 in limited_malloc(png_struct_def*, unsigned long) /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:90:10
    #2 0x56530f in OSS_FUZZ_png_malloc_base /src/libpng/pngmem.c:91:17
    #3 0x56530f in OSS_FUZZ_png_malloc /src/libpng/pngmem.c:179:10
    #4 0x5cd6e8 in OSS_FUZZ_png_read_start_row /src/libpng/pngrutil.c:4607:44
    #5 0x5681e2 in OSS_FUZZ_png_read_update_info /src/libpng/pngread.c:275:10
    #6 0x4a7b4d in LLVMFuzzerTestOneInput /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:192:3
    #7 0x4c7283 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #8 0x4b29e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #9 0x4b828c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #10 0x4e17c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #11 0x7f99aad07082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: __interceptor_malloc--limited_malloc(png_struct_def*, unsigned long)--OSS_FUZZ_png_malloc_base
SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/libpng/pngrutil.c:4079:11 in png_read_filter_row_paeth_multibyte_pixel
Unique heap origins: 58
Stack depot allocated bytes: 9764880
Unique origin histories: 29
History depot allocated bytes: 196608
Exiting
➜  oss-fuzz git:(master) ✗
```

# After the patch

```
➜  oss-fuzz git:(master) ✗ sudo python3 infra/helper.py reproduce libpng libpng_read_fuzzer ../oss/issue424/reproducer
INFO:root:Running: docker run --rm --privileged --platform linux/amd64 -i -v /home/alberto/progetti/oss-fuzz/build/out/libpng:/out -v /home/alberto/progetti/oss/issue424/reproducer:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce libpng_read_fuzzer -runs=100.
+ FUZZER=libpng_read_fuzzer
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer libpng_read_fuzzer -runs=100 /testcase
/out/libpng_read_fuzzer -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase -dict=png.dict < /dev/null
Dictionary: 28 entries
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2091965288
INFO: Loaded 1 modules   (5514 inline 8-bit counters): 5514 [0x6f7db0, 0x6f933a), 
INFO: Loaded 1 PC tables (5514 PCs): 5514 [0x691310,0x6a6bb0), 
/out/libpng_read_fuzzer: Running 1 inputs 100 time(s) each.
Running: /testcase
Executed /testcase in 1 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

```
➜  oss-fuzz git:(master) ✗ sudo python3 infra/helper.py reproduce libpng libpng_read_fuzzer ../oss/issue424/reproducer2
INFO:root:Running: docker run --rm --privileged --platform linux/amd64 -i -v /home/alberto/progetti/oss-fuzz/build/out/libpng:/out -v /home/alberto/progetti/oss/issue424/reproducer2:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce libpng_read_fuzzer -runs=100.
+ FUZZER=libpng_read_fuzzer
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer libpng_read_fuzzer -runs=100 /testcase
/out/libpng_read_fuzzer -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase -dict=png.dict < /dev/null
Dictionary: 28 entries
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2098397282
INFO: Loaded 1 modules   (5514 inline 8-bit counters): 5514 [0x6f7db0, 0x6f933a), 
INFO: Loaded 1 PC tables (5514 PCs): 5514 [0x691310,0x6a6bb0), 
/out/libpng_read_fuzzer: Running 1 inputs 100 time(s) each.
Running: /testcase
Executed /testcase in 1 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
➜  oss-fuzz git:(master) ✗ 
```

### CODE REVIEW

**Comment by thealberto** [comment]
[repro.zip](https://github.com/glennrp/libpng/files/10006585/repro.zip)

**Comment by thealberto** [comment]
Hi @ctruta , I understand that and I'm happy to work on a more precise fix. Within the #424 I also talk about another "dirty" solution which just zeroes the memory chunks. Would you prefer something like that?

Thanks

**Comment by jbowler** [comment]
I think a better explanation is required.  It's pointless memseting the entirety of png_ptr->big_row_buf or png_ptr->prev_row_buf because all the actual row samples are already initialized.  big_row_buf is initialized by the copy of the first row of data out of the zlib window and big_prev_buf is initialized by the memset on line 4681 of pngrutil.c.

The original, possibly somewhat lame, thinking behind this is that it averts any need to check the filter on the first line of the PNG; Paeth, Up and Avg all read the previous line, which does not exist so the code creates a nominally 0 line.  I can't remember if the spec requires this, however IRC it ends up with the same effect as mapping Paeth->Sub and Up->None.  Avg is somewhat unfortunate.

Without this mapping all three lines of pngrutil.c have a problem:

4066: c = *(prev_row - bpp);
4067: a = *(row - bpp);
4068: b = *prev_row++;

Yet it seems that the fuzzer is whining only about either 4066 or 4067 because:

4078: pa = p < 0 ? -p : p;
4079: pb = pc < 0 ? -pc : pc;

Clearly the variables in these lines have been initialized, which is making it very difficult to see which read is being complained about, but:

4078: p is (b - c) which is prev_row[0] - prev_row[-1]
4079: pc is (a - c) which is row[-1] - prev_row[-1]

So this looks like the fuzzer is complaining about row[-1] being uninitialized.

This makes no sense because row[-1] was already read (along with prev_row[-1]) in the while loop at line 4053.

Conclusion: looks like a bug in the fuzzer.

If someone really thinks anything in there is uninitialized I suggest adding a description of how this happens; both row and prev_row have already been initialized and what is more the previous byte in each case has too (that's the filter byte).  The row points point 16 bytes into the big_ pointers (which are the real malloced memory).  IRC the first 15 bytes of the big_* buffers aren't initialized but then I can't see how this code could ever access them!

More analysis required.

**Comment by jbowler** [comment]
Note that this is a duplicate of #424

**Comment by thealberto** [comment]
Thanks, I'll work on another patch

**Pull request closed without merging**
