### PR TITLE
Fix (work round) rgb-to-gray issues in libpng 1.6

### PR DESCRIPTION
**Pull request by jbowler**
The previous attempts to ignore the errors in the code aren't quite enough to
deal with the 'channel selection' encoding added to libpng 1.7; abort.
pngvalid.c is changed to drop this encoding in prior versions.

Signed-off-by: John Bowler <jbowler@acm.org>

### CODE REVIEW

**Comment by glennrp** [comment]
Pull did not work:

Your branch is ahead of 'origin/libpng16' by 5 commits.
  (use "git push" to publish your local commits)
scooby> git merge --no-ff jbowler-libpng16-pngvalid-rgb-to-gray-digitize-issues
merge: jbowler-libpng16-pngvalid-rgb-to-gray-digitize-issues - not something we can merge

**Comment by jbowler** [comment]
Well... you apparently have 5 local commits to libpng16 which you haven't pushed to github; there's nothing I can do about that.  I'm completely up-to-date with both github and sourceforge at this point; i.e. I've back merged all the available changes and I have pushed everything to libpng16-pngvalid-rgb-to-gray-digitize-issues.

**Comment by jbowler** [comment]
Speeling eeror maybe:

git merge congress
merge: congress - not something we can merge

**Comment by glennrp** [comment]
I don't see anything I have not pushed.  git reports "everything is up to date" when I push either libpng16 or libpng17 branch.

**Pull request closed without merging**
