### PR TITLE
Repair of issue 264

### PR DESCRIPTION
**Pull request by tangyaofang**
Repair of issue #264

### CODE REVIEW

**Comment by ctruta** [comment]
@jbowler, for not a very good reason, I postponed the integration of a bunch of fixes implemented by @tangyaofang, and then I forgot about them. (Apologies.)

Could you please review this commit and advise on whether to integrate it? The fix looks good to me, but I would appreciate your opinion also.

**Comment by jbowler** [comment]
This is a duplicate of #294

**Comment by jbowler** [comment]
The fix is not likely to work given the problem.

**Comment by ctruta** [comment]
I see. Admittedly, I haven't tested it. I'm integrating the other solution, proposed by @thealberto in #350.

**Pull request closed without merging**
