### PR TITLE
Coverity fixes, plus a script to make addition test files

### PR DESCRIPTION
**Pull request by jbowler**
Fixes to makepng.c so that it compiles with GCC 5.1.0
contrib/testspngs/; a directory for additional test png files generated by
makepng.  At present some of the files are very large (more than 2MByte) so
until I find a way to reduce the size of these without invalidating the tests
I've just committed the script to generate them.  In the future the real files
need to be here or all the build scripts need updating to make a local (host,
not cross build target) version of makepng.

Signed-off-by: John Bowler <jbowler@acm.org>

### CODE REVIEW

**Comment by glennrp** [comment]
This causes breakage; I'll undo it after merging.
 /* Generate a compiler error if there is an old png.h in the search path. */
-typedef png_libpng_version_1_7_0beta66 Your_png_h_is_not_version_1_7_0beta66;
+typedef png_libpng_version_1_7_0beta65 Your_png_h_is_not_version_1_7_0beta65;

**Comment by jbowler** [comment]
Well, I think I'm completely up to date with your libpng16 branch now and
the *only* occurrences of the string 'beta66' are in the CHANGES file and
pngtest.c; I changed pngtest.c because it didn't compile with 'beta66' in
there.

You probably want to do a git diff of whatever you are testing against
origin/libpng16.

John

On Fri, Sep 18, 2015 at 1:56 PM, Glenn Randers-Pehrson <
notifications@github.com> wrote:

> This causes breakage; I'll undo it after merging.
> /* Generate a compiler error if there is an old png.h in the search path.
> */
> -typedef png_libpng_version_1_7_0beta66
> Your_png_h_is_not_version_1_7_0beta66;
> +typedef png_libpng_version_1_7_0beta65
> Your_png_h_is_not_version_1_7_0beta65;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glennrp/libpng/pull/18#issuecomment-141567313>.
>



-- 
John Bowler <john.cunningham.bowler@gmail.com>
+1 (541) 450-9885
PO BOX 3151
KERBY OR 97531-3151
USA

**Comment by glennrp** [comment]
Done.  Updated beta65 back to beta66.

**Comment by jbowler** [comment]
Looks correct.

John

On Fri, Sep 18, 2015 at 2:39 PM, Glenn Randers-Pehrson <
notifications@github.com> wrote:

> Done. Updated beta65 back to beta66.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glennrp/libpng/pull/18#issuecomment-141575339>.
>



-- 
John Bowler <john.cunningham.bowler@gmail.com>
+1 (541) 450-9885
PO BOX 3151
KERBY OR 97531-3151
USA

**Pull request closed without merging**
