### PR TITLE
Libpng17

### PR DESCRIPTION
**Pull request by jbowler**
This activates the new test files in 'make check'.  Validated on x86_64 across my normal collection of build configurations and GCC versions.

### CODE REVIEW

**Comment by glennrp** [comment]
The license is gone from pngstest-errors.h again.  Was that deliberate?  To avoid having to restore the license manually each time, could we have a "--license" option in makepngs.c?

**Comment by jbowler** [comment]
You removed it in commit 40d90d34 'Add copyright and license to
contrib/testpngs/makepngs.sh'; the commit deleted the printf of the libpng
license.  I assumed you did that deliberately, though the commit did also
contain the merge conflict which made things so complicated; you had
changed the 'Last changed' line in makepng.c but the 'old' line had a date
of September 20, whereas my 'old' line has September 22.

John

On Fri, Sep 25, 2015 at 1:38 PM, Glenn Randers-Pehrson <
notifications@github.com> wrote:

> The license is gone from pngstest-errors.h again. Was that deliberate? To
> avoid having to restore the license manually each time, could we have a
> "--license" option in makepngs.c?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glennrp/libpng/pull/25#issuecomment-143347874>.
>



-- 
John Bowler <john.cunningham.bowler@gmail.com>
+1 (541) 450-9885
PO BOX 3151
KERBY OR 97531-3151
USA

**Comment by jbowler** [comment]
I suggest you just copy contrib/libtests/pngstest.c back from libpng16;
that's the only difference.  pngstest-errors.h differ in the two versions,
but it's just a matter of adding the four license lines back in.

John

On Fri, Sep 25, 2015 at 2:11 PM, John Bowler <
john.cunningham.bowler@gmail.com> wrote:

> You removed it in commit 40d90d34 'Add copyright and license to
> contrib/testpngs/makepngs.sh'; the commit deleted the printf of the libpng
> license.  I assumed you did that deliberately, though the commit did also
> contain the merge conflict which made things so complicated; you had
> changed the 'Last changed' line in makepng.c but the 'old' line had a date
> of September 20, whereas my 'old' line has September 22.
>
> John
>
> On Fri, Sep 25, 2015 at 1:38 PM, Glenn Randers-Pehrson <
> notifications@github.com> wrote:
>
>> The license is gone from pngstest-errors.h again. Was that deliberate? To
>> avoid having to restore the license manually each time, could we have a
>> "--license" option in makepngs.c?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/glennrp/libpng/pull/25#issuecomment-143347874>.
>>
>
>
>
> --
> John Bowler <john.cunningham.bowler@gmail.com>
> +1 (541) 450-9885
> PO BOX 3151
> KERBY OR 97531-3151
> USA
>



-- 
John Bowler <john.cunningham.bowler@gmail.com>
+1 (541) 450-9885
PO BOX 3151
KERBY OR 97531-3151
USA

**Comment by glennrp** [comment]
OK I'll do that.

**Pull request merged**
