### PR TITLE
libpng-manual.txt: remove extraneous semicolon

### PR DESCRIPTION
**Pull request by CorruptedVor**

### CODE REVIEW

**Review by ctruta — CHANGES_REQUESTED** [review]
This is useful, thank you, but I'd like to remove all extraneous semicolons in a single commit, and I can see others still remaining.

**Comment by CorruptedVor** [comment]
Removed the other extra semicolons I could spot. I was specifically looking for more of those function definition ones.

**Comment by ctruta** [comment]
Much better, thank you, but you're still not finished :-)

You need to update both `libpng-manual.txt` and `libpng.3`, in the same way, with the same changes.

Also, I see that your git author name is "CorruptedVor", and your git author email is "51972476+CorruptedVor@users.noreply.github.com". I would strongly prefer a real-world name and a real email address, if at all possible. Even for changes as small as typo corrections, I want the contributors to identify themselves properly, for copyright purposes.

**Review by jbowler — COMMENTED** [review]
I believe the changes are incorrect; the semicolon is both English and C, the meaning is unambiguous with the ";" but potentially confusing without it.  I guess you could add "e.g." before the "{" but it seems unnecessary.  Any human reading the text as is will understand it.

**Comment by ctruta** [comment]
> > Also, I see that your git author name is "CorruptedVor", and your git author email is "[51972476+CorruptedVor@users.noreply.github.com](mailto:51972476+CorruptedVor@users.noreply.github.com)". I would strongly prefer a real-world name and a real email address, if at all possible. Even for changes as small as typo corrections, I want the contributors to identify themselves properly, for copyright purposes.
> 
> On the copyright: I'm not going to identify myself properly

I respect your wish for anonymity, @CorruptedVor.

On the other hand, the libpng documentation, including the programmer's manual, needs a complete overhaul, which I plan on doing at a later time. I don't deny the usefulness of your change, and the libpng license absolutely allows you to make that change on your own. But I won't incorporate that change in the official libpng source tree at this moment, and I'm also not going to debate it any further in this PR.

Feel free to give us (the PNG Group) a ping on `png-mng-implement` at `lists.sourceforge.net`. Although it's been a very quiet discussion list over the last year(s), it is still the most appropriate forum when it comes to debating issues like this one.

Thanks again.

**Pull request closed without merging**
