### PR TITLE
New pull request for merge #13

### PR DESCRIPTION
**Pull request by jbowler**
You closed #13 without merging the changes but with the comment "Merged"; was this deliberate?

You libpng16 branch is at 1e16e88:

https://github.com/glennrp/libpng/commit/1e16e8829d4da77998835ad2dd80bf5c62b6168f

Mine includes the two commits in this pull request and is at e8c5546:

https://github.com/jbowler/libpng-1/commit/e8c554661c31fc4de057ef3071811114f2a621ed

John

### CODE REVIEW

**Comment by glennrp** [comment]
I'll try again.

**Comment by glennrp** [comment]
On Fri, Sep 18, 2015 at 10:51 AM, John Bowler <notifications@github.com>
wrote:

> You closed #13 <https://github.com/glennrp/libpng/pull/13> without
> merging the changes but with the comment "Merged"; was this deliberate?
>

No it was not deliberate.  It should be OK now.  I had a minor disaster
when I pulled the request into
my libpng17 branch, so I made a new clone and started over.

Let me know if there's still anything wrong.


Glenn

**Comment by jbowler** [comment]
https://github.com/jbowler/libpng-1/commit/e8c554661c31fc4de057ef3071811114f2a621ed is missing, well, your spelling corrections are there, but not the code changes.

John

**Comment by glennrp** [comment]
Sometimes it's easier just to do a simple copy from libpng17 to libpng16.
Loses history though.

**Comment by jbowler** [comment]
Yes, it's fixed now.  I've just been copying the libpng17 pngvalid.c each time after I verified it against a libpng16 build, but then I typically check against all the builds that use it before committing a change to libpng17.

**Comment by jbowler** [comment]
Yes, fixed.  My tests on the latest set of Coverity changes passed.  I
think Coverity runs should have -DUNTESTED= because clearly we're not
interested in the fact that a variable cannot have a particular value if
this is only because the branch that sets it ends "UNTESTED".

I didn't haven't fixed the num_passes report yet, it looks like it is
because pngtest.c is not doing anything (other than continuing) if
png_get_IHDR fails; that's a bug, it needs to png_error.  I'll fix it and
commit it to the current pull request.

John
​

**Pull request merged**
