### PR TITLE
Add support for loading images with associated alpha.

### PR DESCRIPTION
**Pull request by ioquatix**
Let me know what you think.

### CODE REVIEW

**Comment by ioquatix** [comment]
I didn't bother writing documentation because I'm not sure what will change... but once we settle on something (or nothing), I can write something.

**Comment by ioquatix** [comment]
One more thing which I think would be useful, would be the ability to save PNG on disk using an associated alpha format. The only real difference is a flag in the binary data stream, and the ability to convert to pre/post multiplied on load as required.

**Comment by ioquatix** [comment]
Oh, one more thing to consider... if the buffer is converted to associated alpha on load, it may also need to be converted back to unassociated on save... unless we directly support that in the file format.

**Comment by glennrp** [comment]
Converting back to non-premultiplied from premultiplied is necessarily lossy.  At the extreme, when alpha is 0 the color samples become 0 as well regardless of their original content.  It's not possible to recover the original underlying color from a {0,0,0,0} pixel.

**Comment by ioquatix** [comment]
@glennrp Absolutely, there is a fundamental difference between associated and un-associated alpha, and the ability to convert between them in either direction is a lossy process.

Both formats require different blending functions, but with modern compositors preferring associated alpha. (iOS CoreImage converts PNGs to associated alpha format, OpenGL, DirectX, Vulkan all only support associated-alpha frame buffers AFAIK).

I think what would make sense is for PNG to add support for associated alpha in the file format, and to allow the user to specify what they want in the pixel buffer. PNG should convert as required.

When saving a file, it should be saved in it's native format, unless the user explicitly requests that it should be converted.

**Comment by ioquatix** [comment]
Taking into consideration the blending function for associated alpha pixels, one can see that when `alpha=0` the blend function becomes additive, which means the `rgb` components are added to the destination. It's a useful trait of the data representation. Just FYI.

**Comment by glennrp** [comment]
There's no real good way to signal that a PNG file contains associated alpha.  It would require either a new chunk (like CgBI but not placed ahead of IHDR) or a revised existing chunk (such as a new field in IHDR).  One possibility would be some additional colortypes, e.g., with bit 4 representing associated alpha (color_type 12: black-white-premultiplied_alpha, 14: color,premultiplied_alpha). Either of these would be incompatible with existing decoders.  Alternatively add a new ancillary chunk to signal that the alpha is associated.  Probably the latter is the only way that is really feasible.

**Comment by ioquatix** [comment]
All good thoughts.

As it seems you know, Apple is already doing something with CoreImage and making pre-multiplied images for iOS. This happens when you compile code with Xcode for iOS deployment. CoreImage somehow detects these mutant PNGs and loads them appropriately. http://iphonedevwiki.net/index.php/CgBI_file_format

I know that at the very least there would be some incompatibility, even if you just load the pixel data, it won't be displayed correctly, but this can be fixed going forward.

In addition, even if applications just get raw pixel data, at least it can be displayed, albeit incorrectly.

Given what we have to deal with, I'd probably vote for a new chunk, but my intuition is not very good since I don't know this project inside out. If you think it should come before the IHDR, but right now Apple doesn't? We can support both but issue a warning for Apple's format?

**Comment by glennrp** [comment]
> If you think it should come before the IHDR, but right now Apple doesn't?
The other way around.  No chunks should come before IHDR.
Apple's CgBI format does other weird things like omitting CRC's and rearranging sample order.

**Comment by ioquatix** [comment]
I see.

I think from a pragmatic point of view.

Let's try to offer Apple a standard way forward that doesn't alienate all the existing users of that tool.

We may disagree with how they did it. We can ignore the file format, but it simply alienates users.

My suggestion is to:

1/ Implement it how we think is best.

2/ At some level, support Apple's implementation where possible. Perhaps optionally emit a warning if the structure doesn't conform to 1 above.

**Comment by ioquatix** [comment]
I just wanted to add, that Apple is probably doing the arrangement of samples in order to maximise throughput when loading from disk. The less work they have to do to get the image into the GPU memory, the better. I think you'll find there are a lot of use cases where this would be of benefit.

**Comment by ioquatix** [comment]
Did you test this code before merging? I think we should consider documentation and tests too..

**Comment by glennrp** [comment]
No, I just put it out there for people to try.  Perhaps it would have been more sensible to put it in libpng17.

**Comment by ioquatix** [comment]
I see. I would like to think that we can bring a more comprehensive solution, but this is a good start.

In my case, I needed to support pre-multiplied alpha in both WebP and PNG, so I finally implemented the conversion a layer up: https://github.com/kurocha/images/blob/master/source/Images/Conversions.cpp - a bit of a hack to get things working and probably worth revisiting at some point. We have to convert 8-bit sRGB from unassociated to associated alpha.

However, I do think it would be a great addition to support it in the format itself.

**Pull request merged**
